### PR TITLE
xfwm4: version bumped to 4.12.2

### PR DESCRIPTION
**Pull request by rtlanceroad**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
Can one of the admins verify this patch?

**Comment by Ratler** [comment]
ok to test

**Comment by Ratler** [comment]
retest this please

**Comment by Ratler** [comment]
retest this please, fixed gobject-introspection dep in gdk-pixbuf.

**Comment by Ratler** [comment]
third time is the charm (retest this please)

Some issues with lingering optional depends in the docker image that runs the CI-test.

**Comment by v4hn** [comment]
retest this please (hehe, third time didn't do it ;) ) Fixed missing optdep in libwnck

**Comment by v4hn** [comment]
retest this please (fixed some hard gobject-introspection dependencies)

**Comment by v4hn** [comment]
retest this please (removed default y to gobject-introspection in gdk-pixbuf)

**Comment by v4hn** [comment]
retest this please (adjusted cairo <-> gobject-introspection dependencies)

**Comment by v4hn** [comment]
retest this please (removed default y in pango)

**Pull request merged**
