### PR TITLE
Version bump to Xfce 4.13.x series and extras

### PR DESCRIPTION
**Pull request by stratact**
While half the work was updating the core Xfce components to 4.13.x, the other half of the work was from @Florin65's repo.

This superceeds https://github.com/lunar-linux/moonbase-xfce/pull/127

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
Can one of the admins verify this patch?

**Comment by Florin65** [comment]
retest this please

**Comment by Florin65** [comment]
Great. Let's see how is going.

**Comment by Ratler** [comment]
ok to test

**Comment by stratact** [comment]
retest this please

**Pull request closed without merging**
