### PR TITLE
xfce4: version bumped to 4.12.0

### PR DESCRIPTION
**Pull request by rtlanceroad**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
Can one of the admins verify this patch?

**Comment by Ratler** [comment]
add to whitelist

**Comment by Ratler** [comment]
retest this please (hopefully jenkins behave this time)

**Comment by Ratler** [comment]
retest this please

**Comment by v4hn** [comment]
retest this please (added missing optdep to libwnck)

**Comment by v4hn** [comment]
retest this please (a lot happened in the meanwhile :) )

**Pull request merged**
