### PR TITLE
xfce4-terminal: version bumped to 0.8.3

### PR DESCRIPTION
**Pull request by bsfc1685**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
Can one of the admins verify this patch?

**Comment by v4hn** [comment]
That version of xfce4-terminal changed its dependency from `vte` to our `vte3` module, you missed that.
But otherwise the commit looks fine. Why did you close it @bsfc1685 ?

**Comment by bsfc1685** [comment]
When I saw "Can one of the admins verify this patch" I had an intuition that some gtk/cairo dep would failed again and wanted one of you handle it instead. Honestly I gave up a little here ^^

**Comment by v4hn** [comment]
Nah, that warning simply means that you are no acknowledged contributor to the `moonbase-xfce` section. Thus, the integration tests are not run until an admin verifies the submission is ok.

Sadly, I never worked with that, so I don't know whether I'm allowed to whitelist you, or how I would do that. So I hoped @Ratler (as the author of the bot) would do that in time :).

Could you reopen the request and change the dependency?

**Pull request closed without merging**
